import { Services } from "@/types";

export const servicesType1: Services[] = [
{
id: "1",
title: "Data Cabling Installation",
description: "iQTEL provides expert data cabling installation services for homes and businesses, ensuring your network infrastructure is robust and reliable. Whether you need internal or external data cabling, our team guarantees a seamless installation process.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Residential"],
},
{
id: "2",
title: "NBN Internet Installation/Repairs",
description: "We specialize in NBN internet installation and repairs, ensuring your connection is set up correctly or restored swiftly. iQTEL technicians are experienced with all aspects of the NBN, providing expert support to keep your internet running smoothly.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Residential"],
},
{
id: "3",
title: "MDF Jumpering",
description: "Our MDF jumpering services ensure your internet and phone lines are connected properly at the main distribution frame (MDF). iQTEL handles all your internal wiring needs, enabling flawless communication services in your building.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Residential"],
},
{
id: "4",
title: "Phone Installation/Repairs",
description: "From new phone installations to repairs, iQTEL offers fast and reliable solutions for both residential and business phone systems. Trust us to keep your phone lines in perfect working order.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Residential"],
},
{
id: "5",
title: "Internet Health Check",
description: "Experiencing slow speeds or connectivity issues? iQTEL offers an internet health check service to diagnose and fix problems with your network, ensuring optimal performance for your internet connection.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Residential"],
},
{
id: "6",
title: "Network Installation",
description: "iQTEL specializes in comprehensive network installation for homes and businesses. From cabling to configuration, we ensure your network infrastructure is strong, efficient, and tailored to your specific needs.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Residential"],
},
{
id: "7",
title: "WIFI Access Point Installation",
description: "Improve your wireless connectivity with iQTEL’s Wi-Fi access point installation services. We’ll ensure you have seamless Wi-Fi coverage throughout your property for uninterrupted internet access.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Residential"],
},
{
id: "8",
title: "CCTV Camera Installation",
description: "Secure your home or business with professional CCTV camera installation from iQTEL. We install high-quality surveillance systems to protect your property and ensure peace of mind.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Residential"],
},
{
id: "9",
title: "NBN NTD, NCD Relocation (Including Fibre)",
description: "Need to relocate your NBN NTD or NCD, including fibre connections? iQTEL offers professional relocation services, ensuring your NBN equipment is installed in the most convenient location for your home or business.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Residential"],
},
{
id: "10",
title: "Bridging Tap Removal",
description: "Our technicians are experts in bridging tap removal, a common cause of slow or unstable internet connections. iQTEL can diagnose and resolve this issue to improve your network’s performance.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Residential"],
},
{
id: "11",
title: "Starlink Installation/Repairs",
description: "iQTEL offers Starlink installation and repair services for those looking to connect to or troubleshoot this innovative satellite internet system. We ensure smooth installation and reliable performance for your Starlink setup.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Residential"],
},
];

export const servicesType2: Services[] = [
{
id: "12",
title: "Internal Fibre Run",
description: "For a reliable, high-speed connection, iQTEL offers internal fibre run services. We handle everything from the cabling to configuration, providing you with an efficient internal fibre network.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Commercial", "Fiber"],
},
{
id: "13",
title: "External Fibre Run",
description: "Need an external fibre network? iQTEL provides external fibre run services, ensuring your fibre optic cabling is installed and maintained with precision and care.",
imageUrl: "/images/main1.png",
category: ["Commercial", "Fiber"],
},
{
id: "14",
title: "Fibre Splicing",
description: "Our fibre splicing services ensure the integrity of your fibre optic connections. iQTEL technicians are experts at joining fibre cables for uninterrupted, high-speed internet.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Commercial", "Fiber"],
},
{
id: "15",
title: "Fibre Repair",
description: "Experiencing issues with your fibre connection? iQTEL offers fast and reliable fibre repair services, ensuring your network stays operational and your connection remains strong.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Commercial", "Fiber"],
},
{
id: "16",
title: "NTD and Fobot Installation/Relocation",
description: "iQTEL provides professional NTD and Fobot installation or relocation services to optimize your network setup. Whether you’re upgrading or moving, our technicians ensure a seamless transition.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Commercial", "Fiber"],
},
{
id: "17",
title: "Network Design",
description: "iQTEL offers custom network design services, tailoring your infrastructure to your unique requirements. Our experts design networks that are efficient, scalable, and future-proof.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Commercial", "Copper"],
},
{
id: "18",
title: "VoIP Phones Installation/Repairs",
description: "Switch to or maintain your VoIP phone system with iQTEL’s expert installation and repair services.We ensure smooth, high-quality communication for your business.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Commercial", "Copper"],
},
{
id: "19",
title: "PABX Installation",
description: "Upgrade your business communication with iQTEL’s PABX installation services. We provide professional, scalable phone systems to meet the needs of your growing company.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Commercial", "Copper"],
},
{
id: "20",
title: "Millimetre Radio Link Installation",
description: "iQTEL specializes in millimetre radio link installation, providing high-speed wireless communication solutions for businesses. Our technicians ensure reliable performance for your radio link setup.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Commercial", "Radio"],
},
{
id: "21",
title: "Line of Sight Analysis",
description: "For optimal radio and wireless network performance, iQTEL conducts thorough line of sight analysis to ensure a clear, unobstructed path between communication points.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Commercial", "Radio"],
},
{
id: "22",
title: "Radio Repairs/Maintenance",
description: "iQTEL offers professional radio repairs and maintenance services to keep your wireless communication systems in top condition. Trust our experts for swift and effective service.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Commercial", "Radio"],
},
{
id: "23",
title: "Starlink Installation/Repairs",
description: "iQTEL offers Starlink installation and repair services for those looking to connect to or troubleshoot this innovative satellite internet system. We ensure smooth installation and reliable performance for your Starlink setup.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Commercial", "Radio"],
},
{
id: "24",
title: "Internet Health Check",
description: "Experiencing slow speeds or connectivity issues? iQTEL offers an internet health check service to diagnose and fix problems with your network, ensuring optimal performance for your internet connection.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Commercial", "Copper"],
},
{
id: "25",
title: "Data Cabling Installation",
description: "iQTEL provides expert data cabling installation services for homes and businesses, ensuring your network infrastructure is robust and reliable. Whether you need internal or external data cabling, our team guarantees a seamless installation process.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Commercial", "Copper"],
},
{
id: "26",
title: "MDF Jumpering",
description: "Our MDF jumpering services ensure your internet and phone lines are connected properly at the main distribution frame (MDF). iQTEL handles all your internal wiring needs, enabling flawless communication services in your building.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Commercial", "Copper"],
},
{
id: "27",
title: "Network Installation",
description: "iQTEL specializes in comprehensive network installation for homes and businesses. From cabling to configuration, we ensure your network infrastructure is strong, efficient, and tailored to your specific needs.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Commercial", "Copper"],
},
{
id: "28",
title: "CCTV Camera Installation",
description: "Secure your home or business with professional CCTV camera installation from iQTEL. We install high-quality surveillance systems to protect your property and ensure peace of mind.",
imageUrl: "/images/blogs/blog-post-1.jpg",
category: ["Commercial", "Copper"],
},
];
